apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-login
spec:
  selector:
    matchLabels:
      app: github-login
  replicas: 2
  template:
    metadata:
      labels:
        app: github-login
    spec:
      containers:
        - name: github-login
          image: abdullahyoudsf961/github-login
          ports:
            - containerPort: 4000